server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: "Solicitudes"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}

routes:
  paths:
    solicitud: ${ROUTE_SOLICITUD:/api/v1/solicitud}

adapters:
  r2dbc:
    host: ${POSTGRES_HOST:localhost}
    port: ${POSTGRES_PORT:5432}
    database: ${POSTGRES_DB:solicitudes}
    schema: ${POSTGRES_SCHEMA:public}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  secret-is-base64: ${JWT_SECRET_IS_BASE64:true}

webClient:
  microAutenticacion: ${WEBCLIENT_MICRO_AUTENTICACION:http://localhost:8080/api/v1/usuario}
