server:
  port: 8080
spring:
  application:
    name: "Solicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    solicitud: "/api/v1/solicitud"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "solicitudes"
    schema: "public"
    username: "postgres"
    password: "root"


jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  secret-is-base64: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG