CREATE TABLE rol (
     rol_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     nombre    VARCHAR(100)  NOT NULL,
     descripcion VARCHAR(255) NOT NULL,
     CONSTRAINT ck_rol_nombres_not_blank     CHECK (btrim(nombre) <> ''),
     CONSTRAINT ck_rol_descripcion_not_blank CHECK (btrim(descripcion) <> '')
);

CREATE TABLE usuario (
     usuario_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     nombres            TEXT NOT NULL CHECK (length(btrim(nombres)) > 0),
     apellidos          TEXT NOT NULL CHECK (length(btrim(apellidos)) > 0),
     fecha_nacimiento   DATE,
     direccion          TEXT,
     telefono           TEXT,
     correo_electronico TEXT NOT NULL UNIQUE,
     contrasenia        TEXT NOT NULL CHECK (length(btrim(contrasenia)) > 0),
     salario_base       NUMERIC(19,2) NOT NULL,
     rol_id             BIGINT NOT NULL,
     CONSTRAINT chk_usuario_email_not_blank CHECK (length(btrim(correo_electronico)) > 0),
     CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES rol (rol_id)
);

CREATE INDEX idx_usuario_rol_id ON usuario (rol_id);