server:
  port: "${REPORTES_SERVER_PORT:8082}"
spring:
  application:
    name: "reporte"
  devtools:
    add-properties: false
  profiles:
    include: null
aws:
  dynamodb:
    endpoint: "${DYNAMO_DB_REPORTES_URL:}"
entrypoint:
  sqs:
    region: "${AWS_REGION:}"
    queueUrl: "${SQS_REPORTE_SOLICITUD_APROBADA:}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
