CREATE TABLE estado (
    estado_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    CONSTRAINT chk_estado_nombre_not_blank CHECK (length(btrim(nombre)) > 0),
    CONSTRAINT chk_estado_descripcion_not_blank CHECK (length(btrim(descripcion)) > 0)
);

CREATE TABLE tipo_prestamo (
   tipo_prestamo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nombre                VARCHAR(120) NOT NULL,
   monto_minimo          NUMERIC(19,2) NOT NULL,
   monto_maximo          NUMERIC(19,2) NOT NULL,
   tasa_interes          NUMERIC(7,4)  NOT NULL,
   validacion_automatica BOOLEAN       NOT NULL,
   CONSTRAINT chk_tp_nombre_not_blank CHECK (length(btrim(nombre)) > 0)
);

CREATE TABLE solicitud (
   solicitud_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   monto             NUMERIC(19,2) NOT NULL,
   plazo             INTEGER NOT NULL,
   correo_electronico VARCHAR(255) NOT NULL,
   estado_id         BIGINT NOT NULL,
   tipo_prestamo_id  BIGINT NOT NULL,
   usuario_id        BIGINT NOT NULL,
   CONSTRAINT chk_solicitud_email_not_blank CHECK (length(btrim(correo_electronico)) > 0),
   CONSTRAINT fk_solicitud_estado FOREIGN KEY (estado_id) REFERENCES estado(estado_id),
   CONSTRAINT fk_solicitud_tipo_prestamo FOREIGN KEY (tipo_prestamo_id) REFERENCES tipo_prestamo(tipo_prestamo_id)
);

CREATE INDEX idx_solicitud_estado ON solicitud (estado_id);
CREATE INDEX idx_solicitud_tipo_prestamo ON solicitud (tipo_prestamo_id);