server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: "Autenticacion"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}

routes:
  paths:
    usuario: ${ROUTE_USUARIO:/api/v1/usuario}
    authentication: ${ROUTE_AUTENTICACION:/api/v1/auth}

adapters:
  r2dbc:
    host: ${POSTGRES_HOST:localhost}
    port: ${POSTGRES_PORT:5432}
    database: ${POSTGRES_DB:autenticacion}
    schema: ${POSTGRES_SCHEMA:public}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}