server:
  port: ${AUTENTICACION_SERVER_PORT:8080}

spring:
  application:
    name: "Autenticacion"

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}

routes:
  paths:
    usuario: ${ROUTE_USUARIO:/api/v1/usuario}
    authentication: ${ROUTE_AUTENTICACION:/api/v1/auth}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}
